### ISSUE TITLE
[Bug] Prevent indent when generate in list

### ISSUE THREAD

**Issue by Quorafind** [Pierrad/obsidian-github-copilot#10]
When want to generate text in list, press `tab` would indent current list rather than select generated text.

**Comment by Pierrad** [comment]
Hi @Quorafind,

I did not achieve to reproduce your problem, as you can see from my screencast and the `keypresses viewer`, in a list when I press `tab`, it accepts the current suggestion instead of creating a new indentation in the list : 

https://github.com/Pierrad/obsidian-github-copilot/assets/32339081/0ff50147-07d7-4617-bf6e-3c64cfa5f477


But I think the problem is that, in my raw obsidian testing valt, I cannot indent a list with a `tab` press, how do you achieve that in a base obsidian setup?

**Comment by Pierrad** [comment]
Hi @Quorafind,

I've added a fix to use `Tab` in a list. It will indent if no suggestion is proposed or accept suggestion if proposed. See #12 for screencast and details. 

You can update to `1.0.1` to retrieve this fix.

**Comment by Quorafind** [comment]
I found that it is possible this is Obsidian Outliner that caused the bug. It works correctly after disabling it. But yes this fix is good! Thank you!
