### ISSUE TITLE
Next suggestion shortcut doesn't work on macOS

### ISSUE THREAD

**Issue by luminati** [Pierrad/obsidian-github-copilot#32]
**Describe the bug**

The shortcut should move to the next suggestion in the list. I tried many mappings, but none of them work.

**To Reproduce**
1. Go to 'New note'
2. Write text until multiple suggestions [eg. 1/2] appear.
3. Press the Keyboard shortcut on macOS Sonoma 
4. See no change in suggestion

**Expected behavior**
The shortcut should move to the next suggestion in the list without any issues.

**Screenshots**
If applicable, add screenshots to help explain your problem with console logs if possible.

**Obsidian and environment (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Obsidian version: Version 1.6.7
 - Plugin version [e.g. 1.0.0] : Version: 1.0.10

**Additional context**

**Comment by Pierrad** [comment]
Hi @luminati, 

Thanks for using the plugin!

Can you list me the plugin you use? I am using macOS with the same version as yours so I don't think it depends on this. Example : 

https://github.com/user-attachments/assets/f3b9b021-bb60-4ba2-98be-4bb062748f96

There's a great chance that one of the plugins shortcuts is taking the precedence over my configuration and that's why the shortcut is not working.

**Comment by luminati** [comment]
I tried it today and it didn't work for me. However, after initial testing, I disabled the global hotkeys plugin, reset all keybindings, and tried to use the default ones. Once I hit the "request suggestions", I could finally select the past first suggestion with the shortcut.
I am closing this bug since it must have been an issue with my setup.
Thank you. Amazing plugin 🚀
