### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by kublaios** [Pierrad/obsidian-github-copilot#39]
**Describe the solution you'd like**
It would be great to be able to use this plugin on mobile devices like iPads

**Describe alternatives you've considered**
[obsidian-copilot](https://github.com/logancyang/obsidian-copilot) recently [implemented](https://github.com/logancyang/obsidian-copilot/pull/513) this but it doesn't have Github Copilot support and to be honest I like this plugin being lightweight and using autocompletion while editing.

**Comment by Pierrad** [comment]
Hi @kublaios, 

The problem is that my plugin needs a NodeJS runtime to execute the copilot core in the background. I don't think you can install a NodeJS executable in iPadOS / iOS and reference it in the plugin settings. 

I looked at the implementation you linked but they removed all NodeJS dependencies to use browser alternatives. I need to create child process for the copilot core, I don't think I can implement that in a browser environment only.

**Comment by kublaios** [comment]
@Pierrad Got it, thanks for looking into it. I hoped that there was an easy way but apparently not... Feel free to close this or save for later :)
